language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      services: xvfb
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
           
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages: clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      dist: xenial
      compiler: clang

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo apt-get install xorg-dev
- sudo apt-get install libgl1-mesa-dev
- sudo apt-get install mesa-common-dev

script: 
- git submodule update --init --recursive
- mkdir _build
- cd _build
- cmake -DBUILD_TESTS=ON -DUSE_OPENGL=OFF ..
- cmake --build . --config RELEASE
- bin/RELEASE/tests
- echo 4 > run.txt
- bin/RELEASE/SimEngineLauncher < run.txt
